# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77baae3a8cc121b1e627ae6b7f0b1390382cd36edccb45f4b97736af6ab100a9a0af71a4a46ea32b9808584c21014569bff96b72476925b63b57e2086b20bf8d
  s3_region: us-west-2
  s3_access_key_id: AKIAIDEKJNK3D5PTZIYA
  s3_secret_access_key: 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
  s3_bucket: polcode-hot-or-not

test:
  secret_key_base: 59a11fa84faf1ac8a8f22f1e50583cda9e6efce93bfd2a2bd278725c0b57376dc9f37a9c279a2caf67ea7ed626f13be83b4d8624b560fc72707729aa35e163e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_region: <%= ENV['region'] %>
  s3_access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
  s3_secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>
  s3_bucket: <%= ENV['BUCKET'] %>
